analyzers:
  ros__parameters:
    path: Aggregation
    lidar:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Lidar
      contains: [ '/lidar' ]
    ouster:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Ouster
      startswith: [ '/ouster' ]
    topology:
      type: 'diagnostic_aggregator/AnalyzerGroup'
      path: Topology
      analyzers:
        livox:
          type: diagnostic_aggregator/GenericAnalyzer
          path: Livox
          contains: [ '/Livox' ]
